version: '3.8'
services:

  echo-mysql:
    image: mysql:5.7
    container_name: echo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: echo_sample
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_ROOT_PASSWORD: password
    # MySQLの文字コードを指定する
    volumes:
      # DBデータの永続化
      - "./Docker/mysql/data:/var/lib/mysql"
      # MySQL起動時にDBを作成し、初期データの投入する
      - "./Docker/mysql/sql:/docker-entrypoint-initdb.d"
      - "./Docker/mysql/my.cnf:/etc/mysql/conf.d/etc-mysql.cnf"

  echo-go:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: echo-go
    tty: true
    ports:
      - 3000:8080
    working_dir: /app
    volumes:
      - ./app:/go/src/app

  echo-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: echo-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=echo-mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - echo-mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
